
import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import Navbar from "@/components/Navbar";
import getCurrentUser from "@/app/actions/getCurrentUser";
import {Metadata} from "next";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const currentUser = await getCurrentUser();

    console.log('currentUser', currentUser)
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar currentUser={currentUser}/>
        {children}

        <Script type="text/javascript"
                src="//dapi.kakao.com/v2/maps/sdk.js?appkey=2ffaeacf6d3cc3827abb93dbe25a0659&libraries=services,clusterer&autoload=false"/>

        </body>
        </html>
    );
}
