
import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import Navbar from "@/components/Navbar";
import getCurrentUser from "@/app/actions/getCurrentUser";
import {Metadata} from "next";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser}/>
        {children}
      </body>
    </html>
  )
}
