#version: "3"
#services:
#    db:
#        image: postgres:latest
#        restart: always
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_USER: "postgres"
#            POSTGRES_PASSWORD: "password"
#        volumes:
#            - ./data:/var/lib/postgresql/data


version: '3.1'

services:

    mysql:
        image: mysql:latest
        container_name: my_mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: 2245
            MYSQL_DATABASE: test
            MYSQL_USER: donggu
            MYSQL_PASSWORD: 2245
        ports:
            - "3306:3306"
